(()=>{
const STORAGE_KEY='marocvows-lang';
const supported=['en','ar','fr','es'];
const labels={en:'English',ar:'العربية',fr:'Français',es:'Español'};
const messages={
ar:{
'Language':'اللغة','Directory':'الدليل','Browse providers':'تصفح مقدمي الخدمات','Back to directory':'العودة إلى الدليل','Wedding help':'مساعدة الزفاف','For professionals':'للمهنيين','Contact':'التواصل','About':'من نحن','Privacy':'الخصوصية','Privacy Policy':'سياسة الخصوصية','Terms':'الشروط','Terms of Use':'شروط الاستخدام','Community Guidelines':'قواعد المجتمع','Plan my event':'خطط لمناسبتي','View profile':'عرض الملف','Full profile':'الملف الكامل','Official website':'الموقع الرسمي','View on map':'عرض على الخريطة','Email':'البريد الإلكتروني','Call':'اتصال','WhatsApp':'واتساب','Account':'الحساب','Quick sign in':'دخول سريع',
'Plan your event':'خطط لمناسبتك','Build your wedding or party team.':'كوّن فريق زفافك أو مناسبتك.','Choose your event, city and the services you need. MarocVows will turn that into a practical provider checklist you can browse one category at a time.':'اختر نوع المناسبة والمدينة والخدمات التي تحتاجها. سيحوّل MarocVows اختياراتك إلى قائمة عملية لمقدمي الخدمات يمكنك تصفحها فئةً بعد فئة.','Event type':'نوع المناسبة','Wedding':'زفاف','Engagement':'خطوبة','Birthday':'عيد ميلاد','Family celebration':'احتفال عائلي','Corporate event':'فعالية مهنية','Other event':'مناسبة أخرى','City':'المدينة','Which services do you need?':'ما الخدمات التي تحتاجها؟','Build my provider checklist':'أنشئ قائمة مقدمي الخدمات','I need personal help':'أحتاج مساعدة شخصية','This planning tool works in your browser and does not submit your selections to MarocVows.':'تعمل أداة التخطيط داخل متصفحك ولا ترسل اختياراتك إلى MarocVows.','Your provider checklist':'قائمة مقدمي الخدمات','Choose at least one available service.':'اختر خدمة متاحة واحدة على الأقل.','currently listed in this city':'مدرج حالياً في هذه المدينة','provider':'مقدم خدمة','providers':'مقدمو خدمات','Browse →':'تصفح ←',
'Venue / hall':'قاعة / فضاء','Caterer':'ممون حفلات','Wedding / event planner':'منظم زفاف / مناسبات','DJ / entertainment':'دي جي / ترفيه','Photographer':'مصور','Videographer':'مصور فيديو','Decoration':'الديكور','Flowers':'الزهور','Beauty / makeup':'التجميل / المكياج','Henna':'الحناء','Live music':'موسيقى حية','Transport':'النقل','Cake / pastry':'الحلويات / الكعك','Equipment / rentals':'المعدات / التأجير',
'Shortlist':'قائمة مختصرة','Compare providers side by side.':'قارن مقدمي الخدمات جنباً إلى جنب.','Use public profile information and genuine MarocVows review signals to narrow your options. Always confirm availability, pricing, service details and contract terms directly with the provider.':'استخدم معلومات الملفات العامة وإشارات تقييمات MarocVows الحقيقية لتضييق اختياراتك. أكّد دائماً التوفر والأسعار وتفاصيل الخدمة وشروط العقد مباشرة مع مقدم الخدمة.','No providers selected.':'لم يتم اختيار أي مقدم خدمة.','Return to the directory and add up to three providers to compare.':'ارجع إلى الدليل وأضف ما يصل إلى ثلاثة مقدمي خدمات للمقارنة.','MarocVows reviews':'تقييمات MarocVows','Profile status':'حالة الملف','Contact check':'التحقق من التواصل','Location':'الموقع','Services':'الخدمات','Claimed profile':'ملف مُطالب به','Unclaimed listing':'قائمة غير مُطالب بها','Verified by MarocVows':'تم التحقق بواسطة MarocVows','Not yet verified by MarocVows':'لم يتم التحقق بعد بواسطة MarocVows','New · no approved reviews yet':'جديد · لا توجد تقييمات معتمدة بعد',
'Vendor profile':'ملف مقدم الخدمة','Directory listing':'قائمة الدليل','Wedding professional':'مهني خدمات الزفاف','Wedding & event service':'خدمة زفاف ومناسبات','Ask MarocVows for help':'اطلب مساعدة MarocVows','Services found':'الخدمات المتوفرة','Public listing snapshot':'ملخص القائمة العامة','Before booking':'قبل الحجز','Confirm availability, exact deliverables, service area, total pricing, deposits and cancellation terms directly with the provider. MarocVows helps with discovery and comparison; it does not guarantee availability or service quality.':'أكد التوفر والخدمات المحددة ومنطقة الخدمة والسعر الإجمالي والعربون وشروط الإلغاء مباشرة مع مقدم الخدمة. يساعد MarocVows في الاكتشاف والمقارنة ولا يضمن التوفر أو جودة الخدمة.','Plan with confidence':'خطط بثقة','Questions worth asking before you commit':'أسئلة مفيدة قبل الالتزام',
'Availability':'التوفر','Guest capacity':'سعة الضيوف','Menu & service':'القائمة والخدمة','Price & terms':'السعر والشروط','Capacity':'السعة','Included facilities':'المرافق المشمولة','Coverage':'التغطية','Delivery':'التسليم','Price & rights':'السعر والحقوق','Music & style':'الموسيقى والأسلوب','Equipment':'المعدات','Scope':'نطاق الخدمة','Supplier coordination':'تنسيق الموردين','Design scope':'نطاق التصميم','Portfolio':'نماذج الأعمال','Setup & removal':'التركيب والإزالة','Design':'التصميم','Substitutions':'البدائل','Price & delivery':'السعر والتسليم','Trial':'التجربة','Price & travel':'السعر والتنقل','Style':'الأسلوب','Timing':'التوقيت','Inventory':'المخزون','Delivery & setup':'التسليم والتركيب','Price & damage':'السعر والأضرار','What is included':'ما الذي يشمله العرض','Experience':'الخبرة',
'Fès · Morocco':'فاس · المغرب','Wedding caterers in Fès':'مموّنو الأعراس في فاس','Explore wedding caterers and event professionals currently listed across Fès. Use MarocVows to compare options, then confirm every commercial detail directly with the provider.':'استكشف مموّني الأعراس ومهنيي المناسبات المدرجين حالياً في فاس. استخدم MarocVows للمقارنة ثم أكد جميع التفاصيل التجارية مباشرة مع مقدم الخدمة.','Fès booking checklist':'قائمة التحقق للحجز في فاس','Compare more than the menu':'قارن أكثر من مجرد القائمة','For larger weddings, ask how many staff are included, whether table service and equipment are included, how transport is handled, what time setup begins, and how the final guest count affects the total price.':'للأعراس الكبيرة، اسأل عن عدد أفراد الطاقم وما إذا كانت خدمة الطاولات والمعدات مشمولة وكيف يتم النقل ووقت بدء التجهيز وكيف يؤثر العدد النهائي للضيوف على السعر.',
'Meknès · Morocco':'مكناس · المغرب','Wedding caterers in Meknès':'مموّنو الأعراس في مكناس','Browse wedding caterers and event services currently listed in Meknès. Compare location and contact information, then verify availability, services and pricing directly.':'تصفح مموّني الأعراس وخدمات المناسبات المدرجة حالياً في مكناس. قارن الموقع ومعلومات التواصل ثم تحقق مباشرة من التوفر والخدمات والأسعار.','Meknès booking checklist':'قائمة التحقق للحجز في مكناس','Get the full service scope in writing':'احصل على نطاق الخدمة كاملاً كتابةً','Confirm what the quote includes, especially staff, service hours, tableware, transport, setup, cleanup and any overtime. For destination families, keep one written contact thread for every change to the booking.':'أكد ما يشمله العرض، خصوصاً الطاقم وساعات الخدمة وأدوات المائدة والنقل والتجهيز والتنظيف وأي ساعات إضافية. احتفظ بسجل مكتوب لكل تغيير في الحجز.',
'Khénifra · Middle Atlas':'خنيفرة · الأطلس المتوسط','Wedding caterers in Khénifra':'مموّنو الأعراس في خنيفرة','Start with local wedding caterers and event professionals currently listed by MarocVows. Contact providers directly and confirm availability, pricing, menu, guest capacity and service area before booking.':'ابدأ بمموّني الأعراس والمهنيين المحليين المدرجين حالياً على MarocVows. تواصل معهم مباشرة وأكد التوفر والأسعار والقائمة وسعة الضيوف ومنطقة الخدمة قبل الحجز.','Before you book':'قبل الحجز','What to compare in Khénifra':'ما الذي تقارنه في خنيفرة','Ask each provider for a written breakdown covering menu, staffing, setup, transport, equipment, guest capacity, deposit, cancellation terms and final price. If you are organising from abroad, confirm who your local point of contact will be and how changes are approved.':'اطلب من كل مقدم خدمة تفصيلاً مكتوباً يشمل القائمة والطاقم والتجهيز والنقل والمعدات وسعة الضيوف والعربون وشروط الإلغاء والسعر النهائي. إذا كنت تنظم من الخارج، أكد جهة الاتصال المحلية وكيفية اعتماد التغييرات.',
'Verified directory listing':'قائمة موثقة في الدليل','MarocVows trust snapshot':'ملخص الثقة من MarocVows','New · no approved MarocVows reviews yet · Unclaimed listing':'جديد · لا توجد تقييمات MarocVows معتمدة بعد · قائمة غير مُطالب بها','Weddings':'أعراس','Private celebrations':'احتفالات خاصة','Birthdays':'أعياد ميلاد','Exclusive events':'فعاليات حصرية','Wedding & celebration venue':'فضاء للأعراس والاحتفالات',
'Continue with Google':'المتابعة عبر Google','Continue with Facebook':'المتابعة عبر Facebook','I agree to the':'أوافق على','and acknowledge the':'وأقر بالاطلاع على','I’m looking for caterers, venues, planners, DJs, photographers or other wedding services.':'أبحث عن مموني حفلات أو قاعات أو منظمين أو دي جي أو مصورين أو خدمات زفاف أخرى.','I’m a caterer, venue, planner, DJ, photographer or another wedding professional.':'أنا ممون حفلات أو قاعة أو منظم أو دي جي أو مصور أو مهني زفاف آخر.',
'Not sure which caterer, venue, planner, DJ or other professional fits your wedding? Send the important details once. MarocVows can review the request and help you narrow the options instead of making you search blindly.':'لست متأكداً أي ممون أو قاعة أو منظم أو دي جي أو مهني يناسب زفافك؟ أرسل التفاصيل المهمة مرة واحدة وسيساعدك MarocVows على تضييق الخيارات.','1. Tell us your city, approximate date, guest count and what services you need.':'1. أخبرنا بالمدينة والتاريخ التقريبي وعدد الضيوف والخدمات التي تحتاجها.','2. We review the request against the providers and local information available to MarocVows.':'2. نراجع طلبك مقارنةً بمقدمي الخدمات والمعلومات المحلية المتاحة لدى MarocVows.','3. We can suggest a practical shortlist to investigate. You still confirm price, availability, contracts and final details directly with each provider.':'3. يمكننا اقتراح قائمة مختصرة عملية. ويبقى عليك تأكيد السعر والتوفر والعقود والتفاصيل النهائية مباشرة مع كل مقدم خدمة.','Wedding-help requests are tied to a private MarocVows account so you can see the request status later.':'ترتبط طلبات مساعدة الزفاف بحساب MarocVows خاص حتى تتمكن من متابعة حالتها لاحقاً.','Prefer not to say yet':'أفضل عدم التحديد الآن','Under 30,000 MAD':'أقل من 30,000 درهم','30,000–70,000 MAD':'30,000–70,000 درهم','70,000–150,000 MAD':'70,000–150,000 درهم','150,000–300,000 MAD':'150,000–300,000 درهم','300,000+ MAD':'300,000+ درهم','Wedding venue':'قاعة زفاف','Wedding planner':'منظم زفاف','Cook / kitchen team':'طباخ / فريق مطبخ','Decoration':'الديكور','Music / band':'موسيقى / فرقة','Beauty / makeup':'تجميل / مكياج','Henna':'حناء','Cake / pastry':'كعك / حلويات','Other':'أخرى',
'If you provide a real wedding service in Morocco, you can send your business details for review. Submitting does not automatically publish a listing; MarocVows checks the information first.':'إذا كنت تقدم خدمة زفاف حقيقية في المغرب، يمكنك إرسال بيانات نشاطك للمراجعة. الإرسال لا ينشر القائمة تلقائياً؛ يراجع MarocVows المعلومات أولاً.','Caterers, wedding venues, wedding planners, cooks and kitchen teams, DJs, photographers, videographers, decorators, bands and musicians, florists, beauty professionals, henna artists, wedding transport providers, cake and pastry businesses, event-rental companies, and other legitimate wedding services.':'يمكن لمموني الحفلات وقاعات الزفاف والمنظمين والطباخين وفرق المطابخ والدي جي والمصورين ومصوري الفيديو ومصممي الديكور والفرق الموسيقية وبائعي الزهور ومهنيي التجميل والحناء والنقل والحلويات وتأجير المعدات وغيرها من خدمات الزفاف الشرعية التقديم.','Provider applications require an account so the applicant can later see the review status and correct information if needed.':'تتطلب طلبات مقدمي الخدمات حساباً حتى يتمكن مقدم الطلب من متابعة حالة المراجعة وتصحيح المعلومات عند الحاجة.',
'Loading…':'جارٍ التحميل…','This is not a booking form. It simply helps MarocVows understand your wedding and the services you may need.':'هذا ليس نموذج حجز. إنه يساعد MarocVows فقط على فهم زفافك والخدمات التي قد تحتاجها.','What would you like help finding? Choose all that apply.':'ما الذي تريد المساعدة في العثور عليه؟ اختر كل ما ينطبق.','Venue / wedding hall':'قاعة / فضاء زفاف','Negafa / traditional dressing':'نكافة / اللباس التقليدي','Band / orchestra / traditional music':'فرقة / أوركسترا / موسيقى تقليدية','Cook / kitchen team':'طباخ / فريق مطبخ','Hair / makeup / beauty':'شعر / مكياج / تجميل','Henna artist':'نقاشة حناء','Furniture / equipment rental':'تأجير الأثاث / المعدات','Invitations / guest gifts':'دعوات / هدايا الضيوف','Entertainment':'ترفيه','Something else':'شيء آخر','Choose every service you provide. A business can offer more than one category.':'اختر كل خدمة تقدمها. يمكن للنشاط تقديم أكثر من فئة.','Services you offer — choose all that apply.':'الخدمات التي تقدمها — اختر كل ما ينطبق.','Wedding planner / manager':'منظم / مدير زفاف','Florist':'بائع زهور','Wedding cars / transport':'سيارات الزفاف / النقل','Other wedding service':'خدمة زفاف أخرى'
},
fr:{
'Language':'Langue','Directory':'Annuaire','Browse providers':'Voir les prestataires','Back to directory':'Retour à l’annuaire','Wedding help':'Aide mariage','For professionals':'Pour les professionnels','Contact':'Contact','About':'À propos','Privacy':'Confidentialité','Privacy Policy':'Politique de confidentialité','Terms':'Conditions','Terms of Use':'Conditions d’utilisation','Community Guidelines':'Règles de la communauté','Plan my event':'Planifier mon événement','View profile':'Voir la fiche','Full profile':'Fiche complète','Official website':'Site officiel','View on map':'Voir sur la carte','Email':'E-mail','Call':'Appeler','WhatsApp':'WhatsApp','Account':'Compte','Quick sign in':'Connexion rapide',
'Plan your event':'Planifiez votre événement','Build your wedding or party team.':'Construisez l’équipe de votre mariage ou événement.','Choose your event, city and the services you need. MarocVows will turn that into a practical provider checklist you can browse one category at a time.':'Choisissez votre événement, votre ville et les services dont vous avez besoin. MarocVows les transforme en une liste pratique de prestataires à parcourir catégorie par catégorie.','Event type':'Type d’événement','Wedding':'Mariage','Engagement':'Fiançailles','Birthday':'Anniversaire','Family celebration':'Fête familiale','Corporate event':'Événement professionnel','Other event':'Autre événement','City':'Ville','Which services do you need?':'De quels services avez-vous besoin ?','Build my provider checklist':'Créer ma liste de prestataires','I need personal help':'J’ai besoin d’aide personnalisée','This planning tool works in your browser and does not submit your selections to MarocVows.':'Cet outil fonctionne dans votre navigateur et n’envoie pas vos choix à MarocVows.','Your provider checklist':'Votre liste de prestataires','Choose at least one available service.':'Choisissez au moins un service disponible.','currently listed in this city':'actuellement référencé(s) dans cette ville','provider':'prestataire','providers':'prestataires','Browse →':'Voir →',
'Venue / hall':'Lieu / salle','Caterer':'Traiteur','Wedding / event planner':'Organisateur mariage / événement','DJ / entertainment':'DJ / animation','Photographer':'Photographe','Videographer':'Vidéaste','Decoration':'Décoration','Flowers':'Fleurs','Beauty / makeup':'Beauté / maquillage','Henna':'Henné','Live music':'Musique live','Transport':'Transport','Cake / pastry':'Gâteau / pâtisserie','Equipment / rentals':'Matériel / location',
'Shortlist':'Sélection','Compare providers side by side.':'Comparez les prestataires côte à côte.','Use public profile information and genuine MarocVows review signals to narrow your options. Always confirm availability, pricing, service details and contract terms directly with the provider.':'Utilisez les informations publiques et les signaux d’avis MarocVows pour affiner vos choix. Confirmez toujours disponibilité, tarifs, détails du service et conditions contractuelles directement avec le prestataire.','No providers selected.':'Aucun prestataire sélectionné.','Return to the directory and add up to three providers to compare.':'Retournez à l’annuaire et ajoutez jusqu’à trois prestataires à comparer.','MarocVows reviews':'Avis MarocVows','Profile status':'Statut de la fiche','Contact check':'Vérification du contact','Location':'Localisation','Services':'Services','Claimed profile':'Fiche revendiquée','Unclaimed listing':'Fiche non revendiquée','Verified by MarocVows':'Vérifié par MarocVows','Not yet verified by MarocVows':'Pas encore vérifié par MarocVows','New · no approved reviews yet':'Nouveau · aucun avis approuvé',
'Vendor profile':'Fiche prestataire','Directory listing':'Fiche d’annuaire','Wedding professional':'Professionnel du mariage','Wedding & event service':'Service mariage & événement','Ask MarocVows for help':'Demander de l’aide à MarocVows','Services found':'Services identifiés','Public listing snapshot':'Résumé de la fiche publique','Before booking':'Avant de réserver','Confirm availability, exact deliverables, service area, total pricing, deposits and cancellation terms directly with the provider. MarocVows helps with discovery and comparison; it does not guarantee availability or service quality.':'Confirmez directement avec le prestataire la disponibilité, les prestations exactes, la zone de service, le prix total, les acomptes et les conditions d’annulation. MarocVows aide à découvrir et comparer, sans garantir disponibilité ni qualité.','Plan with confidence':'Planifiez avec confiance','Questions worth asking before you commit':'Questions utiles avant de vous engager',
'Availability':'Disponibilité','Guest capacity':'Capacité invités','Menu & service':'Menu & service','Price & terms':'Prix & conditions','Capacity':'Capacité','Included facilities':'Équipements inclus','Coverage':'Couverture','Delivery':'Livraison','Price & rights':'Prix & droits','Music & style':'Musique & style','Equipment':'Équipement','Scope':'Périmètre','Supplier coordination':'Coordination fournisseurs','Design scope':'Périmètre du design','Portfolio':'Portfolio','Setup & removal':'Installation & démontage','Design':'Design','Substitutions':'Substitutions','Price & delivery':'Prix & livraison','Trial':'Essai','Price & travel':'Prix & déplacement','Style':'Style','Timing':'Timing','Inventory':'Inventaire','Delivery & setup':'Livraison & installation','Price & damage':'Prix & dommages','What is included':'Ce qui est inclus','Experience':'Expérience',
'Fès · Morocco':'Fès · Maroc','Wedding caterers in Fès':'Traiteurs de mariage à Fès','Explore wedding caterers and event professionals currently listed across Fès. Use MarocVows to compare options, then confirm every commercial detail directly with the provider.':'Découvrez les traiteurs de mariage et professionnels de l’événement actuellement référencés à Fès. Comparez avec MarocVows puis confirmez chaque détail commercial directement avec le prestataire.','Fès booking checklist':'Checklist de réservation à Fès','Compare more than the menu':'Comparez plus que le menu','For larger weddings, ask how many staff are included, whether table service and equipment are included, how transport is handled, what time setup begins, and how the final guest count affects the total price.':'Pour les grands mariages, demandez combien de personnes sont incluses, si le service à table et le matériel sont compris, comment le transport est géré, quand commence l’installation et comment le nombre final d’invités influence le prix.',
'Meknès · Morocco':'Meknès · Maroc','Wedding caterers in Meknès':'Traiteurs de mariage à Meknès','Browse wedding caterers and event services currently listed in Meknès. Compare location and contact information, then verify availability, services and pricing directly.':'Parcourez les traiteurs et services événementiels actuellement référencés à Meknès. Comparez localisation et contacts, puis vérifiez directement disponibilité, services et tarifs.','Meknès booking checklist':'Checklist de réservation à Meknès','Get the full service scope in writing':'Obtenez le périmètre complet par écrit','Confirm what the quote includes, especially staff, service hours, tableware, transport, setup, cleanup and any overtime. For destination families, keep one written contact thread for every change to the booking.':'Confirmez ce que le devis inclut, notamment le personnel, les horaires, la vaisselle, le transport, l’installation, le nettoyage et les heures supplémentaires. Gardez une trace écrite de chaque modification.',
'Khénifra · Middle Atlas':'Khénifra · Moyen Atlas','Wedding caterers in Khénifra':'Traiteurs de mariage à Khénifra','Start with local wedding caterers and event professionals currently listed by MarocVows. Contact providers directly and confirm availability, pricing, menu, guest capacity and service area before booking.':'Commencez par les traiteurs et professionnels locaux actuellement référencés sur MarocVows. Contactez-les directement et confirmez disponibilité, prix, menu, capacité et zone de service avant de réserver.','Before you book':'Avant de réserver','What to compare in Khénifra':'Que comparer à Khénifra','Ask each provider for a written breakdown covering menu, staffing, setup, transport, equipment, guest capacity, deposit, cancellation terms and final price. If you are organising from abroad, confirm who your local point of contact will be and how changes are approved.':'Demandez à chaque prestataire un détail écrit du menu, personnel, installation, transport, équipement, capacité, acompte, annulation et prix final. Si vous organisez depuis l’étranger, confirmez votre contact local et la façon dont les changements sont approuvés.',
'Verified directory listing':'Fiche d’annuaire vérifiée','MarocVows trust snapshot':'Résumé de confiance MarocVows','New · no approved MarocVows reviews yet · Unclaimed listing':'Nouveau · aucun avis MarocVows approuvé · fiche non revendiquée','Weddings':'Mariages','Private celebrations':'Célébrations privées','Birthdays':'Anniversaires','Exclusive events':'Événements exclusifs','Wedding & celebration venue':'Lieu de mariage & célébration',
'Continue with Google':'Continuer avec Google','Continue with Facebook':'Continuer avec Facebook','I agree to the':'J’accepte les','and acknowledge the':'et reconnais avoir lu la','I’m looking for caterers, venues, planners, DJs, photographers or other wedding services.':'Je recherche des traiteurs, lieux, organisateurs, DJs, photographes ou autres services de mariage.','I’m a caterer, venue, planner, DJ, photographer or another wedding professional.':'Je suis traiteur, lieu, organisateur, DJ, photographe ou autre professionnel du mariage.',
'Not sure which caterer, venue, planner, DJ or other professional fits your wedding? Send the important details once. MarocVows can review the request and help you narrow the options instead of making you search blindly.':'Vous ne savez pas quel traiteur, lieu, organisateur, DJ ou autre professionnel correspond à votre mariage ? Envoyez les informations importantes une seule fois et MarocVows vous aide à affiner vos options.','1. Tell us your city, approximate date, guest count and what services you need.':'1. Indiquez votre ville, date approximative, nombre d’invités et services recherchés.','2. We review the request against the providers and local information available to MarocVows.':'2. Nous examinons la demande avec les prestataires et informations locales disponibles sur MarocVows.','3. We can suggest a practical shortlist to investigate. You still confirm price, availability, contracts and final details directly with each provider.':'3. Nous pouvons suggérer une sélection pratique. Vous confirmez ensuite prix, disponibilité, contrats et détails directement avec chaque prestataire.','Wedding-help requests are tied to a private MarocVows account so you can see the request status later.':'Les demandes d’aide mariage sont liées à un compte privé MarocVows afin de suivre leur statut.','Prefer not to say yet':'Je préfère ne pas préciser','Under 30,000 MAD':'Moins de 30 000 MAD','30,000–70,000 MAD':'30 000–70 000 MAD','70,000–150,000 MAD':'70 000–150 000 MAD','150,000–300,000 MAD':'150 000–300 000 MAD','300,000+ MAD':'300 000+ MAD','Wedding venue':'Lieu de mariage','Wedding planner':'Organisateur de mariage','Cook / kitchen team':'Cuisinier / équipe cuisine','Music / band':'Musique / groupe','Beauty / makeup':'Beauté / maquillage','Henna':'Henné','Cake / pastry':'Gâteau / pâtisserie','Other':'Autre',
'If you provide a real wedding service in Morocco, you can send your business details for review. Submitting does not automatically publish a listing; MarocVows checks the information first.':'Si vous proposez un véritable service de mariage au Maroc, vous pouvez envoyer les informations de votre activité pour examen. L’envoi ne publie pas automatiquement une fiche : MarocVows vérifie d’abord les informations.','Caterers, wedding venues, wedding planners, cooks and kitchen teams, DJs, photographers, videographers, decorators, bands and musicians, florists, beauty professionals, henna artists, wedding transport providers, cake and pastry businesses, event-rental companies, and other legitimate wedding services.':'Traiteurs, lieux de mariage, organisateurs, cuisiniers, DJs, photographes, vidéastes, décorateurs, groupes, fleuristes, professionnels beauté, artistes henné, transport, pâtisserie, location événementielle et autres services légitimes peuvent candidater.','Provider applications require an account so the applicant can later see the review status and correct information if needed.':'Les candidatures prestataires nécessitent un compte afin de suivre leur statut et corriger les informations si nécessaire.',
'Loading…':'Chargement…','This is not a booking form. It simply helps MarocVows understand your wedding and the services you may need.':'Ceci n’est pas un formulaire de réservation. Il aide simplement MarocVows à comprendre votre mariage et les services dont vous pourriez avoir besoin.','What would you like help finding? Choose all that apply.':'Que souhaitez-vous trouver ? Choisissez toutes les options utiles.','Venue / wedding hall':'Lieu / salle de mariage','Negafa / traditional dressing':'Negafa / tenue traditionnelle','Band / orchestra / traditional music':'Groupe / orchestre / musique traditionnelle','Hair / makeup / beauty':'Coiffure / maquillage / beauté','Henna artist':'Artiste henné','Furniture / equipment rental':'Location mobilier / matériel','Invitations / guest gifts':'Invitations / cadeaux invités','Entertainment':'Animation','Something else':'Autre chose','Choose every service you provide. A business can offer more than one category.':'Choisissez tous les services que vous proposez. Une activité peut appartenir à plusieurs catégories.','Services you offer — choose all that apply.':'Services proposés — choisissez tout ce qui s’applique.','Wedding planner / manager':'Organisateur / manager de mariage','Florist':'Fleuriste','Wedding cars / transport':'Voitures de mariage / transport','Other wedding service':'Autre service de mariage'
},
es:{
'Language':'Idioma','Directory':'Directorio','Browse providers':'Ver proveedores','Back to directory':'Volver al directorio','Wedding help':'Ayuda para la boda','For professionals':'Para profesionales','Contact':'Contacto','About':'Sobre nosotros','Privacy':'Privacidad','Privacy Policy':'Política de privacidad','Terms':'Términos','Terms of Use':'Términos de uso','Community Guidelines':'Normas de la comunidad','Plan my event':'Planificar mi evento','View profile':'Ver perfil','Full profile':'Perfil completo','Official website':'Sitio oficial','View on map':'Ver en el mapa','Email':'Correo electrónico','Call':'Llamar','WhatsApp':'WhatsApp','Account':'Cuenta','Quick sign in':'Acceso rápido',
'Plan your event':'Planifica tu evento','Build your wedding or party team.':'Crea el equipo de tu boda o evento.','Choose your event, city and the services you need. MarocVows will turn that into a practical provider checklist you can browse one category at a time.':'Elige tu evento, ciudad y los servicios que necesitas. MarocVows los convierte en una lista práctica de proveedores para revisar categoría por categoría.','Event type':'Tipo de evento','Wedding':'Boda','Engagement':'Compromiso','Birthday':'Cumpleaños','Family celebration':'Celebración familiar','Corporate event':'Evento corporativo','Other event':'Otro evento','City':'Ciudad','Which services do you need?':'¿Qué servicios necesitas?','Build my provider checklist':'Crear mi lista de proveedores','I need personal help':'Necesito ayuda personalizada','This planning tool works in your browser and does not submit your selections to MarocVows.':'Esta herramienta funciona en tu navegador y no envía tus selecciones a MarocVows.','Your provider checklist':'Tu lista de proveedores','Choose at least one available service.':'Elige al menos un servicio disponible.','currently listed in this city':'actualmente listado(s) en esta ciudad','provider':'proveedor','providers':'proveedores','Browse →':'Ver →',
'Venue / hall':'Lugar / salón','Caterer':'Catering','Wedding / event planner':'Organizador de bodas / eventos','DJ / entertainment':'DJ / entretenimiento','Photographer':'Fotógrafo','Videographer':'Videógrafo','Decoration':'Decoración','Flowers':'Flores','Beauty / makeup':'Belleza / maquillaje','Henna':'Henna','Live music':'Música en vivo','Transport':'Transporte','Cake / pastry':'Tarta / pastelería','Equipment / rentals':'Equipo / alquileres',
'Shortlist':'Selección','Compare providers side by side.':'Compara proveedores lado a lado.','Use public profile information and genuine MarocVows review signals to narrow your options. Always confirm availability, pricing, service details and contract terms directly with the provider.':'Usa la información pública y las señales de reseñas reales de MarocVows para reducir opciones. Confirma siempre disponibilidad, precios, detalles del servicio y condiciones del contrato directamente con el proveedor.','No providers selected.':'No hay proveedores seleccionados.','Return to the directory and add up to three providers to compare.':'Vuelve al directorio y añade hasta tres proveedores para comparar.','MarocVows reviews':'Reseñas MarocVows','Profile status':'Estado del perfil','Contact check':'Verificación de contacto','Location':'Ubicación','Services':'Servicios','Claimed profile':'Perfil reclamado','Unclaimed listing':'Ficha no reclamada','Verified by MarocVows':'Verificado por MarocVows','Not yet verified by MarocVows':'Aún no verificado por MarocVows','New · no approved reviews yet':'Nuevo · sin reseñas aprobadas',
'Vendor profile':'Perfil del proveedor','Directory listing':'Ficha del directorio','Wedding professional':'Profesional de bodas','Wedding & event service':'Servicio de bodas y eventos','Ask MarocVows for help':'Pedir ayuda a MarocVows','Services found':'Servicios encontrados','Public listing snapshot':'Resumen de la ficha pública','Before booking':'Antes de reservar','Confirm availability, exact deliverables, service area, total pricing, deposits and cancellation terms directly with the provider. MarocVows helps with discovery and comparison; it does not guarantee availability or service quality.':'Confirma directamente con el proveedor disponibilidad, servicios exactos, zona, precio total, depósitos y cancelación. MarocVows ayuda a descubrir y comparar; no garantiza disponibilidad ni calidad.','Plan with confidence':'Planifica con confianza','Questions worth asking before you commit':'Preguntas útiles antes de comprometerte',
'Availability':'Disponibilidad','Guest capacity':'Capacidad de invitados','Menu & service':'Menú y servicio','Price & terms':'Precio y condiciones','Capacity':'Capacidad','Included facilities':'Instalaciones incluidas','Coverage':'Cobertura','Delivery':'Entrega','Price & rights':'Precio y derechos','Music & style':'Música y estilo','Equipment':'Equipo','Scope':'Alcance','Supplier coordination':'Coordinación de proveedores','Design scope':'Alcance del diseño','Portfolio':'Portafolio','Setup & removal':'Montaje y retirada','Design':'Diseño','Substitutions':'Sustituciones','Price & delivery':'Precio y entrega','Trial':'Prueba','Price & travel':'Precio y desplazamiento','Style':'Estilo','Timing':'Horario','Inventory':'Inventario','Delivery & setup':'Entrega y montaje','Price & damage':'Precio y daños','What is included':'Qué incluye','Experience':'Experiencia',
'Fès · Morocco':'Fez · Marruecos','Wedding caterers in Fès':'Catering de bodas en Fez','Explore wedding caterers and event professionals currently listed across Fès. Use MarocVows to compare options, then confirm every commercial detail directly with the provider.':'Explora servicios de catering y profesionales de eventos actualmente listados en Fez. Compara con MarocVows y confirma después cada detalle comercial directamente con el proveedor.','Fès booking checklist':'Lista de reserva en Fez','Compare more than the menu':'Compara más que el menú','For larger weddings, ask how many staff are included, whether table service and equipment are included, how transport is handled, what time setup begins, and how the final guest count affects the total price.':'Para bodas grandes, pregunta cuántas personas incluye el equipo, si se incluyen servicio de mesa y material, cómo se gestiona el transporte, cuándo empieza el montaje y cómo afecta el número final de invitados al precio.',
'Meknès · Morocco':'Meknes · Marruecos','Wedding caterers in Meknès':'Catering de bodas en Meknes','Browse wedding caterers and event services currently listed in Meknès. Compare location and contact information, then verify availability, services and pricing directly.':'Consulta catering y servicios de eventos actualmente listados en Meknes. Compara ubicación y contacto y confirma directamente disponibilidad, servicios y precios.','Meknès booking checklist':'Lista de reserva en Meknes','Get the full service scope in writing':'Obtén por escrito todo el alcance del servicio','Confirm what the quote includes, especially staff, service hours, tableware, transport, setup, cleanup and any overtime. For destination families, keep one written contact thread for every change to the booking.':'Confirma qué incluye el presupuesto, especialmente personal, horarios, vajilla, transporte, montaje, limpieza y horas extra. Mantén un registro escrito de cada cambio.',
'Khénifra · Middle Atlas':'Jenifra · Atlas Medio','Wedding caterers in Khénifra':'Catering de bodas en Jenifra','Start with local wedding caterers and event professionals currently listed by MarocVows. Contact providers directly and confirm availability, pricing, menu, guest capacity and service area before booking.':'Empieza con catering y profesionales locales actualmente listados por MarocVows. Contacta directamente y confirma disponibilidad, precios, menú, capacidad y zona de servicio antes de reservar.','Before you book':'Antes de reservar','What to compare in Khénifra':'Qué comparar en Jenifra','Ask each provider for a written breakdown covering menu, staffing, setup, transport, equipment, guest capacity, deposit, cancellation terms and final price. If you are organising from abroad, confirm who your local point of contact will be and how changes are approved.':'Pide a cada proveedor un desglose escrito de menú, personal, montaje, transporte, equipo, capacidad, depósito, cancelación y precio final. Si organizas desde el extranjero, confirma tu contacto local y cómo se aprueban los cambios.',
'Verified directory listing':'Ficha verificada del directorio','MarocVows trust snapshot':'Resumen de confianza MarocVows','New · no approved MarocVows reviews yet · Unclaimed listing':'Nuevo · sin reseñas MarocVows aprobadas · ficha no reclamada','Weddings':'Bodas','Private celebrations':'Celebraciones privadas','Birthdays':'Cumpleaños','Exclusive events':'Eventos exclusivos','Wedding & celebration venue':'Lugar para bodas y celebraciones',
'Continue with Google':'Continuar con Google','Continue with Facebook':'Continuar con Facebook','I agree to the':'Acepto los','and acknowledge the':'y reconozco la','I’m looking for caterers, venues, planners, DJs, photographers or other wedding services.':'Busco catering, lugares, organizadores, DJs, fotógrafos u otros servicios de boda.','I’m a caterer, venue, planner, DJ, photographer or another wedding professional.':'Soy catering, lugar, organizador, DJ, fotógrafo u otro profesional de bodas.',
'Not sure which caterer, venue, planner, DJ or other professional fits your wedding? Send the important details once. MarocVows can review the request and help you narrow the options instead of making you search blindly.':'¿No sabes qué catering, lugar, organizador, DJ u otro profesional encaja con tu boda? Envía los datos importantes una vez y MarocVows te ayudará a reducir opciones.','1. Tell us your city, approximate date, guest count and what services you need.':'1. Indica ciudad, fecha aproximada, número de invitados y servicios que necesitas.','2. We review the request against the providers and local information available to MarocVows.':'2. Revisamos la solicitud con los proveedores e información local disponible en MarocVows.','3. We can suggest a practical shortlist to investigate. You still confirm price, availability, contracts and final details directly with each provider.':'3. Podemos sugerir una selección práctica. Tú confirmas precio, disponibilidad, contratos y detalles finales directamente con cada proveedor.','Wedding-help requests are tied to a private MarocVows account so you can see the request status later.':'Las solicitudes de ayuda de boda están vinculadas a una cuenta privada de MarocVows para consultar su estado.','Prefer not to say yet':'Prefiero no indicarlo','Under 30,000 MAD':'Menos de 30.000 MAD','30,000–70,000 MAD':'30.000–70.000 MAD','70,000–150,000 MAD':'70.000–150.000 MAD','150,000–300,000 MAD':'150.000–300.000 MAD','300,000+ MAD':'300.000+ MAD','Wedding venue':'Lugar de boda','Wedding planner':'Organizador de bodas','Cook / kitchen team':'Cocinero / equipo de cocina','Music / band':'Música / grupo','Beauty / makeup':'Belleza / maquillaje','Henna':'Henna','Cake / pastry':'Tarta / pastelería','Other':'Otro',
'If you provide a real wedding service in Morocco, you can send your business details for review. Submitting does not automatically publish a listing; MarocVows checks the information first.':'Si ofreces un servicio real de bodas en Marruecos, puedes enviar los datos de tu negocio para revisión. Enviar no publica automáticamente una ficha; MarocVows comprueba primero la información.','Caterers, wedding venues, wedding planners, cooks and kitchen teams, DJs, photographers, videographers, decorators, bands and musicians, florists, beauty professionals, henna artists, wedding transport providers, cake and pastry businesses, event-rental companies, and other legitimate wedding services.':'Catering, lugares de boda, organizadores, cocineros, DJs, fotógrafos, videógrafos, decoradores, músicos, floristas, profesionales de belleza, henna, transporte, pastelería, alquileres y otros servicios legítimos pueden solicitar una ficha.','Provider applications require an account so the applicant can later see the review status and correct information if needed.':'Las solicitudes de proveedores requieren una cuenta para poder consultar el estado y corregir datos si hace falta.',
'Loading…':'Cargando…','This is not a booking form. It simply helps MarocVows understand your wedding and the services you may need.':'Esto no es un formulario de reserva. Solo ayuda a MarocVows a entender tu boda y los servicios que puedes necesitar.','What would you like help finding? Choose all that apply.':'¿Qué te gustaría encontrar? Elige todo lo que corresponda.','Venue / wedding hall':'Lugar / salón de boda','Negafa / traditional dressing':'Negafa / vestimenta tradicional','Band / orchestra / traditional music':'Banda / orquesta / música tradicional','Hair / makeup / beauty':'Peluquería / maquillaje / belleza','Henna artist':'Artista de henna','Furniture / equipment rental':'Alquiler de mobiliario / equipo','Invitations / guest gifts':'Invitaciones / regalos para invitados','Entertainment':'Entretenimiento','Something else':'Otra cosa','Choose every service you provide. A business can offer more than one category.':'Elige todos los servicios que ofreces. Un negocio puede pertenecer a varias categorías.','Services you offer — choose all that apply.':'Servicios que ofreces — elige todo lo que corresponda.','Wedding planner / manager':'Organizador / coordinador de bodas','Florist':'Florista','Wedding cars / transport':'Coches de boda / transporte','Other wedding service':'Otro servicio de boda'
}
};
function currentLang(){
  const stored=localStorage.getItem(STORAGE_KEY);
  if(supported.includes(stored))return stored;
  const html=(document.documentElement.lang||'').slice(0,2).toLowerCase();
  return supported.includes(html)?html:'en';
}
let lang=currentLang();
function interpolate(str,vars){
  return String(str).replace(/\{(\w+)\}/g,(_,k)=>vars&&vars[k]!=null?String(vars[k]):'');
}
function t(key,vars){
  const value=(messages[lang]&&messages[lang][key])||key;
  return interpolate(value,vars);
}
function translateDynamic(text){
  if(lang==='en')return text;
  let m=text.match(/^Call\s+(.+)$/);
  if(m)return t('Call')+' '+m[1];
  m=text.match(/^✓ Details verified by MarocVows · (.+)$/);
  if(m){
    const prefix=lang==='ar'?'✓ تم التحقق من التفاصيل بواسطة MarocVows · ':lang==='fr'?'✓ Informations vérifiées par MarocVows · ':'✓ Datos verificados por MarocVows · ';
    return prefix+m[1];
  }
  m=text.match(/^(\d+) provider(s?) currently listed in this city$/);
  if(m)return m[1]+' '+(Number(m[1])===1?t('provider'):t('providers'))+' '+t('currently listed in this city');
  return t(text);
}
function replaceTextNode(node){
  if(!node.nodeValue||!node.nodeValue.trim())return;
  const original=node.nodeValue;
  const trimmed=original.trim();
  const translated=translateDynamic(trimmed);
  if(translated===trimmed)return;
  const lead=original.match(/^\s*/)?.[0]||'';
  const tail=original.match(/\s*$/)?.[0]||'';
  node.nodeValue=lead+translated+tail;
}
function translateTree(root=document.body){
  if(!root)return;
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{
    acceptNode(node){
      const p=node.parentElement;
      if(!p||['SCRIPT','STYLE','NOSCRIPT','CODE','PRE','TEXTAREA'].includes(p.tagName))return NodeFilter.FILTER_REJECT;
      return node.nodeValue&&node.nodeValue.trim()?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT;
    }
  });
  const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(replaceTextNode);
  root.querySelectorAll?.('[placeholder]').forEach(el=>{const x=translateDynamic(el.getAttribute('placeholder'));if(x!==el.getAttribute('placeholder'))el.setAttribute('placeholder',x)});
  root.querySelectorAll?.('[aria-label]').forEach(el=>{const x=translateDynamic(el.getAttribute('aria-label'));if(x!==el.getAttribute('aria-label'))el.setAttribute('aria-label',x)});
  root.querySelectorAll?.('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n)});
}
function ensureSwitcher(){
  let select=document.querySelector('#language,[data-language-switcher]');
  if(select)return select;
  const host=document.querySelector('.header-actions');
  if(!host)return null;
  const label=document.createElement('label');label.className='sr-only';label.htmlFor='language';label.textContent=t('Language');
  select=document.createElement('select');select.id='language';select.className='language-select';select.setAttribute('data-language-switcher','');
  supported.forEach(code=>{const option=document.createElement('option');option.value=code;option.textContent=labels[code];select.appendChild(option)});
  host.prepend(select);host.prepend(label);return select;
}
function updateMeta(){
  const title=document.title;
  const mapped=t(title);
  if(mapped!==title)document.title=mapped;
  const meta=document.querySelector('meta[name="description"]');
  if(meta){const val=meta.getAttribute('content')||'';const translated=t(val);if(translated!==val)meta.setAttribute('content',translated)}
}
function apply(root=document){
  document.documentElement.lang=lang;
  document.documentElement.dir=lang==='ar'?'rtl':'ltr';
  const select=ensureSwitcher();
  if(select)select.value=lang;
  translateTree(root===document?document.body:root);
  updateMeta();
}
function setLang(next,{emit=true}={}){
  if(!supported.includes(next))next='en';
  lang=next;localStorage.setItem(STORAGE_KEY,lang);apply(document);
  if(emit)document.dispatchEvent(new CustomEvent('marocvows:languagechange',{detail:{lang}}));
}
function bind(){
  const select=ensureSwitcher();
  if(select&&!select.dataset.i18nBound){
    select.dataset.i18nBound='1';
    select.addEventListener('change',e=>setLang(e.target.value));
  }
}
function boot(){bind();apply(document);}
window.MarocVowsI18n={t,getLang:()=>lang,setLang,apply,supported};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();