window.MAROCVOWS_PROVIDERS=[
  {
    "slug": "traiteur-el-moutaouakil",
    "name": "Traiteur El Moutaouakil",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Khénifra",
    "cityKey": "khenifra",
    "address": "CARREFOUR, Khénifra 54000",
    "serviceArea": null,
    "phone": "+212660389807",
    "whatsapp": "+212660389807",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "traiteur-el-ghrabli",
    "name": "Traiteur El Ghrabli",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Khénifra",
    "cityKey": "khenifra",
    "address": "Idriss II, Khénifra 54000",
    "serviceArea": null,
    "phone": "+212661714324",
    "whatsapp": "+212661714324",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "lux-atlas-events",
    "name": "Lux Atlas Events",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Khénifra",
    "cityKey": "khenifra",
    "address": "4 Rue Oum Rabiaa, Hamria, Khénifra",
    "serviceArea": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "deguste",
    "name": "Deguste",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Khénifra",
    "cityKey": "khenifra",
    "address": "Quartier des F.A.R., 1st floor, Khénifra",
    "serviceArea": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "doreve-events-traiteur",
    "name": "DOREVE EVENTS Traiteur",
    "category": "caterer",
    "categoryLabel": "Caterer & event planner",
    "city": "Fès",
    "cityKey": "fes",
    "address": "Etg 2, Fatima Zahrae VN, Ville Nouvelle 1, Bureau 10 Rue Lalla Fatima Zahra, Fès 30000, Morocco",
    "serviceArea": null,
    "phone": "+212657073073",
    "whatsapp": "+212657073073",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": "2026-09-10",
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "traiteur-afrah-metarhri",
    "name": "Traiteur AFRAH.METARHRI",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Fès",
    "cityKey": "fes",
    "address": "Jabal Tghat 2, Fès 30090",
    "serviceArea": null,
    "phone": "+212690989593",
    "whatsapp": "+212690989593",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "afrah-noujoum-fes",
    "name": "Afrah Noujoum Fès",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Fès",
    "cityKey": "fes",
    "address": "Atlas, Route de Sefrou, Fès 30000",
    "serviceArea": null,
    "phone": "+212662078275",
    "whatsapp": "+212662078275",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "traiteur-fes-damo",
    "name": "Traiteur Fès Damo",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Fès",
    "cityKey": "fes",
    "address": "Fès, Morocco",
    "serviceArea": null,
    "phone": "+212674068196",
    "whatsapp": "+212674068196",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "la-gala-luxury-events",
    "name": "La Gala Luxury Events",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Fès",
    "cityKey": "fes",
    "address": "Champs De Course, Magasin 6, 23 Lot Yacouta Bled Tazi Entree Droite, Fès 30000, Morocco",
    "serviceArea": null,
    "phone": "+212662808900",
    "whatsapp": "+212662808900",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": "2026-09-10",
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "chhiouate-fes",
    "name": "Chhiouate Fès",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Fès",
    "cityKey": "fes",
    "address": "Fès 30000",
    "serviceArea": null,
    "phone": "+212661986633",
    "whatsapp": "+212661986633",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "arab-events-traiteur",
    "name": "Arab Events Traiteur",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Fès",
    "cityKey": "fes",
    "address": "Moulay Driss Zerhoun, Fès, Morocco",
    "serviceArea": null,
    "phone": "+212649487580",
    "whatsapp": "+212649487580",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": "2026-09-10",
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "traiteur-bensalem-fes",
    "name": "Traiteur Bensalem Fès",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Fès",
    "cityKey": "fes",
    "address": "Avenue Med El Fassi, Fès 30500",
    "serviceArea": null,
    "phone": "+212661407045",
    "whatsapp": "+212661407045",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "arizona-events",
    "name": "Arizona Events",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Fès",
    "cityKey": "fes",
    "address": "Fès 30050",
    "serviceArea": null,
    "phone": "+212661397454",
    "whatsapp": "+212661397454",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "touche-de-vie-traiteur",
    "name": "Touche de Vie Traiteur",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Fès",
    "cityKey": "fes",
    "address": "Rue Abdelkrim Benjelloun, Fès 30000",
    "serviceArea": null,
    "phone": "+212644677988",
    "whatsapp": "+212644677988",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "mounirs-traiteur-meknes",
    "name": "Mounir's Traiteur Meknes",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Meknès",
    "cityKey": "meknes",
    "address": "Magazin N 2, Avenue Zerektouni, Route Hopital Mohamed V, Meknès 50000, Morocco",
    "serviceArea": null,
    "phone": "+212660404490",
    "whatsapp": "+212660404490",
    "email": null,
    "website": "https://traiteur-meknes-mounirs.com/",
    "instagram": null,
    "description": null,
    "services": [
      "Weddings",
      "Private events",
      "Corporate events",
      "Decoration",
      "Art de la table",
      "Maître d’hôtel"
    ],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": "2026-09-10",
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "allo-pastilla-maroc-group",
    "name": "Allo Pastilla Maroc Group",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Meknès",
    "cityKey": "meknes",
    "address": "1 IMM A2 APPRT 3, RES IBN SINA, Meknès 50100, Morocco",
    "serviceArea": null,
    "phone": "+212687803551",
    "whatsapp": "+212687803551",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "traiteur-family-hamdoune-meknes",
    "name": "Traiteur Family Hamdoune Meknès",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Meknès",
    "cityKey": "meknes",
    "address": "Kamilia, Rue Belair, Meknès 50000",
    "serviceArea": null,
    "phone": "+212665874447",
    "whatsapp": "+212665874447",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "dar-bennouna-traiteur",
    "name": "Dar Bennouna Traiteur",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Meknès",
    "cityKey": "meknes",
    "address": "Meknès, Morocco",
    "serviceArea": null,
    "phone": "+212661948284",
    "whatsapp": "+212661948284",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "fidelity-events-and-traiteur",
    "name": "Fidelity Events & Traiteur",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Meknès",
    "cityKey": "meknes",
    "address": "Ismalia 2, Rue de Fès, Meknès 50000",
    "serviceArea": null,
    "phone": "+212611348724",
    "whatsapp": "+212611348724",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "al-akhawayn-traiteur-meknes",
    "name": "Al-Akhawayn Traiteur Meknes",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Meknès",
    "cityKey": "meknes",
    "address": "Rue Haroun Errachid, Ville Nouvelle, Meknès 50000",
    "serviceArea": null,
    "phone": "+212666035056",
    "whatsapp": "+212666035056",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "bennouna-maitre-traiteur",
    "name": "Bennouna Maître Traiteur",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Meknès",
    "cityKey": "meknes",
    "address": "107 Rue Lahboul, Meknès 50000",
    "serviceArea": null,
    "phone": "+212618031131",
    "whatsapp": "+212618031131",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "harfi-afrah",
    "name": "HARFI AFRAH",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Meknès",
    "cityKey": "meknes",
    "address": "Meknès, Morocco",
    "serviceArea": null,
    "phone": "+212679394928",
    "whatsapp": "+212679394928",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "traiteur-la-belle-famille",
    "name": "Traiteur La Belle Famille",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Meknès",
    "cityKey": "meknes",
    "address": "Haye Asskari, Meknès",
    "serviceArea": null,
    "phone": "+212660331695",
    "whatsapp": "+212660331695",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "traiteur-el-mamounia",
    "name": "Traiteur El Mamounia",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Meknès",
    "cityKey": "meknes",
    "address": "Meknès, Morocco",
    "serviceArea": null,
    "phone": "+212617169650",
    "whatsapp": "+212617169650",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  },
  {
    "slug": "traiteur-brahim-event",
    "name": "Traiteur Brahim Event",
    "category": "caterer",
    "categoryLabel": "Wedding caterer",
    "city": "Meknès",
    "cityKey": "meknes",
    "address": "Ryad, Meknès",
    "serviceArea": null,
    "phone": "+212665971050",
    "whatsapp": "+212665971050",
    "email": null,
    "website": null,
    "instagram": null,
    "description": null,
    "services": [],
    "photos": [],
    "videos": [],
    "claimed": false,
    "verified": false,
    "verifiedAt": null,
    "averageRating": 0,
    "reviewCount": 0,
    "sourceType": "public-directory-research"
  }
];
