(()=>{
const vendors=Object.fromEntries((window.MAROCVOWS_PROVIDERS||[]).map(v=>[v.slug,v]));
const qs=new URLSearchParams(location.search);
const slug=qs.get('slug');
const v=vendors[slug];
const $=s=>document.querySelector(s);
const questionSets={
caterer:[['Availability','Is your event date still open?'],['Guest capacity','How many guests can you serve comfortably?'],['Menu & service','What food, staff, table service and equipment are included?'],['Price & terms','Confirm deposits, extras, transport and cancellation terms in writing.']],
venue:[['Availability','Is the venue available on your date and for your event hours?'],['Capacity','What is the seated and standing guest capacity?'],['Included facilities','Ask about tables, chairs, parking, sound limits, catering rules and cleanup.'],['Price & terms','Confirm rental fee, deposit, overtime and cancellation terms in writing.']],
photographer:[['Availability','Are you available for the full event schedule?'],['Coverage','How many hours and photographers are included?'],['Delivery','When and how will edited photos be delivered?'],['Price & rights','Confirm package price, extras, album/video options and usage rights.']],
videographer:[['Availability','Are you available for the full event schedule?'],['Coverage','What parts of the event and how many cameras are included?'],['Delivery','What final films/clips are delivered and on what timeline?'],['Price & rights','Confirm package price, extras and usage rights.']],
dj:[['Availability','Are you available for the full event and setup time?'],['Music & style','Can you handle your preferred music styles and requests?'],['Equipment','What sound, lighting, microphones and backup equipment are included?'],['Price & terms','Confirm setup, travel, overtime and cancellation terms.']],
band:[['Availability','Is the group available for your event date and schedule?'],['Repertoire','Can they perform the music styles and songs you want?'],['Setup','What sound equipment, stage space and breaks are required?'],['Price & terms','Confirm performance time, travel, overtime and cancellation terms.']],
planner:[['Scope','Which planning and coordination tasks are included?'],['Availability','Will the planner be personally present on the event day?'],['Supplier coordination','Which vendors can they coordinate and what remains your responsibility?'],['Price & terms','Confirm fees, payment milestones and cancellation terms.']],
decorator:[['Design scope','What decoration areas and items are included?'],['Portfolio','Can you see recent work similar to your style and venue?'],['Setup & removal','Who handles installation, timing and cleanup?'],['Price & terms','Confirm rentals, flowers/materials, transport and damage deposits.']],
florist:[['Availability','Can the florist source and prepare flowers for your date?'],['Design','Which bouquets, centerpieces and installations are included?'],['Substitutions','How are seasonal flower substitutions handled?'],['Price & delivery','Confirm delivery, setup, pickup and final price.']],
beauty:[['Availability','Are the artist and any assistants available for your preparation schedule?'],['Trial','Is a trial included or available before the event?'],['Services','Confirm makeup, hair, touch-ups and products included.'],['Price & travel','Confirm travel, early-start fees and cancellation terms.']],
henna:[['Availability','Are you available for the henna event and preparation time?'],['Style','Can you provide the designs and tradition/style you want?'],['Timing','How long should application and drying take?'],['Price & travel','Confirm package, travel and any group-service pricing.']],
transport:[['Availability','Are the vehicles available for your date and route?'],['Capacity','How many passengers and vehicles are included?'],['Timing','Confirm pickup times, waiting time and route changes.'],['Price & terms','Confirm fuel, driver, overtime and cancellation terms.']],
cake:[['Availability','Can the cake be prepared and delivered on your date?'],['Size','How many servings are included?'],['Design & flavors','Confirm design, flavors, allergens and tasting options.'],['Delivery & price','Confirm delivery/setup, deposit and final price.']],
rentals:[['Availability','Are the required items available for your date?'],['Inventory','Confirm exact quantities, dimensions and condition.'],['Delivery & setup','Who handles transport, installation and collection?'],['Price & damage','Confirm rental period, deposits, breakage and overtime charges.']],
other:[['Availability','Confirm availability for your event date and location.'],['What is included','Ask for a precise written scope of service.'],['Experience','Ask for recent relevant examples or references.'],['Price & terms','Confirm total price, payment schedule and cancellation terms.']]
};
const genericQuestions=questionSets.other;

if(!v){$('#profile').innerHTML='<h1>Vendor not found</h1><p><a href="/">Return to the MarocVows directory</a>.</p>';return;}
const publicUrl=`https://www.marocvows.com/vendor-profile.html?slug=${encodeURIComponent(slug)}`;
document.title=`${v.name} | ${v.city} | MarocVows`;
const desc=`View contact, location and service details for ${v.name}, a wedding and event provider listed in ${v.city}, Morocco. Confirm availability, pricing and services directly.`;
let meta=document.querySelector('meta[name="description"]');if(meta)meta.content=desc;
let canonical=document.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical);}canonical.href=publicUrl;
$('#name').textContent=v.name;$('#city').textContent=v.city;$('#address').textContent=v.address;$('#crumb').textContent=v.name;
$('#category').textContent=v.categoryLabel||'Wedding & event service';const questions=questionSets[v.category]||genericQuestions;$('#providerChecklist').innerHTML=questions.map(([a,b])=>`<div><strong>${a}</strong><br><small>${b}</small></div>`).join('');
$('#phoneRow').innerHTML=v.phone?`<a class="primary-btn" data-provider-slug="${v.slug}" data-provider-action="call" href="tel:${v.phone.replace(/\s+/g,'')}">Call ${v.phone}</a>`:'<span class="soft-note">Phone number not currently listed. Confirm contact details independently.</span>';
$('#mapLink').href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(v.address);$('#mapLink').dataset.providerSlug=v.slug;$('#mapLink').dataset.providerAction='map';
if(v.website){const w=$('#websiteLink');w.href=v.website;w.dataset.providerSlug=v.slug;w.dataset.providerAction='website';w.hidden=false;} if(v.whatsapp){const row=$('#phoneRow');row.insertAdjacentHTML('beforeend',`<a class="secondary-btn" data-provider-slug="${v.slug}" data-provider-action="whatsapp" href="https://wa.me/${v.whatsapp.replace(/\D/g,'')}" target="_blank" rel="noopener">WhatsApp</a>`);} if(v.email){$('#phoneRow').insertAdjacentHTML('beforeend',`<a class="secondary-btn" data-provider-slug="${v.slug}" data-provider-action="email" href="mailto:${v.email}">Email</a>`);}
if(v.services&&v.services.length){$('#servicesBlock').hidden=false;$('#services').innerHTML=v.services.map(s=>`<span>${s}</span>`).join('');}
if(v.categoryLabel||v.reviewCount||v.verifiedAt||v.claimed){const box=$('#publicSnapshot');const bits=[];if(v.categoryLabel)bits.push(v.categoryLabel);bits.push(v.reviewCount?`${Number(v.averageRating||0).toFixed(1)}/5 from ${v.reviewCount} approved MarocVows reviews`:'New · no approved MarocVows reviews yet');bits.push(v.claimed?'Claimed profile':'Unclaimed listing');$('#snapshotText').textContent=bits.join(' · ');$('#verifiedStamp').textContent=v.verified?`✓ Details verified by MarocVows · ${v.verifiedAt||'recently'}`:'Details not yet independently verified by MarocVows.';box.classList.add('visible');}
const ld={"@context":"https://schema.org","@type":"LocalBusiness","name":v.name,"address":v.address,"areaServed":v.serviceArea||v.city,"url":publicUrl};if(v.phone)ld.telephone=v.phone;const same=[];if(v.website)same.push(v.website);if(v.instagram)same.push(v.instagram);if(same.length)ld.sameAs=same;document.getElementById('vendorSchema').textContent=JSON.stringify(ld);
})();